server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_voting_system
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey123456789mysecretkey123456789
  expiration: 86400000