server:
  port: 8081

spring:
  # Chuyển mail vào trong mục spring
  mail:
    host: smtp.gmail.com
    port: 587
    username: danhv5879@gmail.com
    password: "hozq aayx vwvg gujz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/e_voting_system
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: mysecretkey123456789mysecretkey123456789
  expiration: 86400000
