version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    network_mode: "host"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    network_mode: "host"

  voter-service:
    build: ./voter-service
    container_name: voter-service
    network_mode: "host"

  election-service:
    build: ./election-service
    container_name: election-service
    network_mode: "host"

  crypto-service:
    build: ./crypto-service
    container_name: crypto-service
    network_mode: "host"

  audit-service:
    build: ./audit-service
    container_name: audit-service
    network_mode: "host"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    network_mode: "host"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    network_mode: "host"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
