server:
  port: 8082

spring:
  application:
    name: voter-service

  datasource:
    url: jdbc:mysql://localhost:3306/e_voting_system
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

Cloudinary:
  cloud-name: dzi4yzwjk
  api-key: 571788156588531
  api-secret: xIxbTMdaX0Pc4RzE3kAgC2kDjMk
