server:
  port: 8082

spring:
  application:
    name: voter-service

  datasource:
    url: jdbc:mysql://localhost:3306/e_voting_system
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # ĐƯA KHỐI MAIL VÀO ĐÂY (Ngang hàng với datasource/jpa bên trong spring)
  mail:
    host: smtp.gmail.com
    port: 587
    username: danhv5879@gmail.com
    password: "hozq aayx vwvg gujz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Sửa lại thành true đầy đủ

Cloudinary:
  cloud-name: dzi4yzwjk
  api-key: 571788156588531
  api-secret: xIxbTMdaX0Pc4RzE3kAgC2kDjMk

# Cấu hình Spring Boot Actuator để expose metrics cho Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Mở các endpoint cần thiết
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name} # Gắn tên ứng dụng vào mọi metric để dễ lọc trong Grafana
